[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.zip",
  "unzip"
]
node = "22.5.1"

[phases.build]
cmds = [
  "php -m | grep zip || (echo 'ZIP extension not loaded' && exit 1)",
  "npm ci --prefer-offline --no-audit",
  "npm run build"
]