[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.zip",
  "php82Extensions.mbstring",
  "php82Extensions.pdo_mysql",
  "php82Extensions.bcmath",
  "php82Extensions.intl",
  "unzip"
]
aptPkgs = ["libzip-dev"]
node = "22.5.1"

[phases.build]
cmds = [
  "npm ci --prefer-offline --no-audit",
  "npm run build"
]